import React from "react";

export const text0 = "Building off of NASA’s original spherical probe attached along a long tail with an empennage, we created a Free body diagram (FBD) (figure 2) to identify forces at play like the tension of a long tether (Fr), weight(mg), drag(Fd), and lift(Fl). Knowing that our empange's stabilizers were likely to be minimal in size, we considered Fl and Fd to be smaller, thus shifting our focus to Fr and mg. Since Fr was going to be provided by a tether and likely support mg enough, we shifted towards stability and prioritized light weight designs. First of all we determined our Fr should be at our center of gravity(cg), which was likely to be where any electronic equipment would be kept. Second, to increase stability we focused on creating a long static margin via a long tail, with our center of pressure being at the end of our tail, much like a rocket.";

export const text1 = "To construct our first prototype we simply put together an approximately 40 inch long  skewer, an 8 inch foam ball, 3D printed foam board holders (to make hot swappable fins), and 4 foam board fins (see figure 3) and tied a string to its center of gravity. To test it we swung it around outside. However this prototype moved in an 8 figure path, in other words not stable at all. We determined that this issue was occurring due to turbulent flow forming behind the foam ball. To address our prototype's first flaws we added a 3D printed cone to cover the back end of the sphere. Then we added a Gopro at the front end to capture images during testing, and a counter weight on our tail. Next we ran a tube across the center of our sphere (along our desired cg) and attached a pair of strings on it and an attachment hoop. Not only would this rod and string system function like a tether/attachment point for testing but a gimbal. Using the counterweight we made sure the cg remained at the middle of the sphere."; 

export const text2 = "To test our prototypes we wanted to mimic wind conditions closest to what this probe would encounter on Venus, here on Earth, or most precisely on Stanford’s campus. We launched from Stanford’s dry lake, Lake Lagunita, with our towbody attached to a large quadcopter from a long string (about 50 feet long). We opted not to use an actual balloon, as the drone could simulate more wind speeds from different directions than a balloon could. Additionally the drone with a long string would keep the tethered experience just as a balloon could. Figure 5, shows the footage from this test. From this test we found instability mostly in small oscillations, however at this point in time we only had visual data to see what occurred during the test. Our next iteration aimed to fix these issues.";

export const text3 = "Throughout our project we used CAD platforms such as Fusion 360 to create parts for our towbody, which was useful as it allowed for additive manufacturing to be accessible, and virtual prototyping. Between Prototype 1 and 2 we added once again a great emphasis to aerodynamic design. At this stage we opted to make our towbody’s body resemble a teardrop as a result."; 

export const text4 = "Our next physical prototype was 3D printed to resemble a teardrop with a long tail. However at its front it has a window in which the go pro sets, sealed off with saran wrap. (figure 6) Additionally there is a cut out at the bottom of this design which hosts yet another Gopro to give us a much more accurate view of what a probe on Venus would capture. Furthermore, this design no longer uses string to connect itself to a ring, but a semicircle that was planned to act like another axis of motion. To add on, this design had onboard IMU sensors to capture more data(see next box)";

export const text5 = "The electronics on board the towbody consisted of an Arduino Nano (microcontroller), BMP280 (Barometer/Altitude sensor), and LSM6DSOX (Accelerometer and Gyroscope), and an SD card breakout board. Currently in this prototype they are connected by a breadboard and help in a 3D printed black box. This is the equipment that enables us to collect data on the behavior of our towbody.";

export const text6 = "Prototype2 test"; 

export const text7 = "data details"; 

export const text8 = "Prototype 3";