export const Oldtext0 = "Building off of NASA’s original spherical probe attached along a long tail with an empennage, we created a Free body diagram (FBD) (Bottom or Left Image) to identify forces at play like the tension of a long tether (Fr), weight(mg), drag(Fd), and lift(Fl). Knowing that our empange's stabilizers were likely to be minimal in size, we considered Fl and Fd to be smaller, thus shifting our focus to Fr and mg. Since Fr was going to be provided by a tether and likely support mg enough, we shifted towards stability and prioritized light weight designs. First of all we determined our Fr should be at our center of gravity(cg), which was likely to be where any electronic equipment would be kept. Second, to increase stability we focused on creating a long static margin via a long tail, with our center of pressure being at the end of our tail, much like a rocket.";

export const text0 = "The original concept body comes from JPL’s TOBIAS research. Building off of JPL’s design, we experimented with different components. Starting off with a physical analysis, we studied the different forces that the towbody would experience, as well as the torques they would impart on the system. The center of gravity of the towbody must lie beneath the attachment point by necessity, so that the towbody will stay nadir-facing. Therefore, any non-vertical acceleration of the system will induce a moment in the system, since there is now a separation between the anchor point and CG, as well as a component of the force that is inducing a moment. This led us to add a horizontal stabilizer to add aerodynamic stabilization in the pitch axis. We also used a marionette gimbal in our final design.";

export const text1 = "We built our first prototype from a wooden dowel (1 m length), a styrofoam sphere (20 cm diameter), 3D printed fin holders, and foamcore fins (see top or furthest left image). We attached a tether (single attachment point) to its center of gravity. However, spherical objects in airflow result in boundary layer separation off the back of the sphere: the towbody would produce a turbulent wake. We noticed this when testing the dynamics of the prototype: in airflow, it moved in a figure-8 path. Though statically stable, this prototype was not dynamically stable. To reduce boundary layer separation, we added a 3D printed cone aft of the sphere. We also added a Gopro at the front end to capture images during testing, and to act as a counterweight for the tail. We attached the tether to a rod running a few centimeters above the center of gravity and above it, so that the towbody would settle to a nadir-faing position, similar to a damped pendulum."; 

export const text2 = "To test our prototypes, we wanted to mimic wind conditions closest to what the probe would encounter on Venus. To replicate this on earth, we launched from Stanford’s Lake Lagunita dry lakebed, with our towbody attached to a large quadcopter from a long tether (about 15 meters long). We opted not to use an actual balloon, as the drone could simulate greater wind speeds from different directions than a balloon in Earth’s atmosphere. The drone setup would replicate some of the tether dynamics of the balloon-towbody system, albeit with a significantly shorter tether. The Video below or to the left, shows the footage from this test. From this test we found instability mostly in small, high- oscillations, however at this point in time we only had visual data to see what occurred during the test. Our next iteration aimed to fix these issues.";

export const text3 = "We modeled multiple iterations of our prototype throughout the process to 3D print components. Throughout our project we used CAD platforms such as Fusion 360 to create parts for our towbody, which was useful as it allowed for additive manufacturing to be accessible, and virtual prototyping us to rapidly iterate and 3D print parts. Between Prototype I and II we added once again a great emphasis to aerodynamic designaimed to find an aerodynamically optimal body shape. At this stage, we opted to make our towbody’s body resemble a teardrop to make it as aerodynic as possible. settled on a ‘teardrop’-shaped body, to reduce boundary layer separation."; 

export const text4 = "Our next physical prototype was 3D printed to create our last prototype but with a teardrop like bodyl. However at its front it has a window in which the go pro sets, sealed off with saran wrap. (Top or furthest left image) Additionally there is a cut out at the bottom of this design which hosts yet another Gopro to give us a much more accurate view of what a probe on Venus would capture(Bottom or closest left image). Furthermore, this design no longer uses string to connect itself to a ring, but a semicircle that was planned to act like another axis of motion. To add on, this design had onboard IMU sensors to capture more data (see electronics)";

export const text5 = "The electronics on board the towbody consisted of an Arduino Nano (microcontroller), BMP280 (Barometer/Altitude sensor), and LSM6DSOX (Accelerometer and Gyroscope), and an SD card breakout board. Prototype 3 also features a pitot tube, to measure the windspeed experienced by the towbody. Currently in this prototype they are connected by a breadboard and held in a 3D printed box. This equipment enables us to collect data on the behavior of our towbody. The electronics were programmed to collect data in intervals of 10 milliseconds. Collecting Temperature, pressure, altitude, acceleration in x, y, and z axis, and rotation in x, y, z axis. Prototype 2 uses a forward and downward facing camera, and Prototype 3 features a downward facing camera alone, with the forward-facing camera replaced by a counterweight and Pitot tube.";

export const text6 = "During the test of prototype II,  we observed significantly improved stability . It was much more aerodynamic, however we did see that the semicircle was not really adding any axis of rotation, or contributing to a better design. Furthermore, the GoPro used at the bottom of the probe, fell out of place mod flight and only recorded its “stabilize mode”, making our footage less than ideal for analysis. On the other hand, however, our electronics were successful in data collection (more details in the next box)."; 

export const text7 = "The charts to the left show the data collected by our onboard IMU. Our graphs depict pitch, yaw, and roll rates of the towbody in radians per second over the whole flight. The graphs show intervals of uninterrupted flight, punctuated by towbody turns, represented as spikes in the yaw and roll axes. We see a similar baseline level of angle rates in both: between ~0.25-0.5 rad/s. Prototype 3, with a large static margin and larger tail fins, more consistently stayed within these bounds, but Prototype 2 was more variable, with some ‘stable’ intervals, where the pitch, roll, and yaw rates were consistently lower: approx. 0.1-0.15 rad/s. This difference may have been caused by the smaller tail size: the towbody would be less sensitive to the prevailing wind currents. Also a notable difference is the roll axis. With prototype 2, the roll axis was constrained by the gimballing setup. Prototype 3 includes a ‘marionette gimbal’, to allow it to rotate freely. With this improvement, the roll rate went from the largest rate to the smallest."; 

export const text8 = "This prototype came with a few improvements over the previous iteration. The marionette gimbal allows the towbody to rotate freely, and translate to an extent. This setup is simpler mechanically than a traditional pivoting gimbal, but functions similarly. This prototype also was created with an aluminum backbone, rather than the wooden dowels of the previous prototype. This provided additional rigidity to the system. The tail was also reworked from the previous prototypes, with an increased static margin and tail area."; 

export const text9="This prototype came with a few improvements over the previous iteration. The marionette gimbal allows the towbody to rotate freely, and translate to an extent. This setup is simpler mechanically than a traditional pivoting gimbal, but functions similarly. This prototype also was created with an aluminum backbone, rather than the wooden dowels of the previous prototype. This provided additional rigidity to the system. The tail was also reworked from the previous prototypes, with an increased static margin and tail area."; 

export const WindCannonTesting = "The drone tests mimic the towbody’s actual usage on Venus, including tether dynamics and accelerations in the system. However, we sought to create a more controlled testing setup for the towbody. We create a ‘Wind Cannon’: a stationary setup to produce a stream of laminar air. This testing setup allowed us to study the dynamics of the towbody alone, independent of tether dynamics. The wind cannon consists of an industrial fan with a laminarizing section, reaching peak windspeeds of 4-5 m/s.";